export const MODULES_PERMISSIONS = {
  STORE_MANAGEMENT: {
    key: 'STORE_MANAGEMENT',
    permissions: {
      READ_STORE: 'READ_STORE',
      CREATE_STORE: 'CREATE_STORE',
      EDIT_STORE: 'EDIT_STORE',
      DELETE_STORE: 'DELETE_STORE',
      DOWNLOAD_STORE: 'DOWNLOAD_STORE'
    }
  },
  PRODUCT_MANAGEMENT: {
    key: 'PRODUCT_MANAGEMENT',
    permissions: {
      READ_PRODUCT: 'READ_PRODUCT',
      CREATE_PRODUCT: 'CREATE_PRODUCT',
      EDIT_PRODUCT: 'EDIT_PRODUCT',
      DELETE_PRODUCT: 'DELETE_PRODUCT',
      DOWNLOAD_PRODUCT: 'DOWNLOAD_PRODUCT'
    }
  },
  ORDER_MANAGEMENT: {
    key: 'ORDER_MANAGEMENT',
    permissions: {
      READ_ORDER: 'READ_ORDER',
      CHANGE_ORDER_STORE: 'CHANGE_ORDER_STORE',
      DOWNLOAD_ORDER: 'DOWNLOAD_ORDER',
      CANCEL_ORDER: 'CANCEL_ORDER'
    }
  },
  COUPON_MANAGEMENT: {
    key: 'COUPON_MANAGEMENT',
    permissions: {
      READ_COUPON: 'READ_COUPON',
      CREATE_COUPON: 'CREATE_COUPON',
      EDIT_COUPON: 'EDIT_COUPON',
      DELETE_COUPON: 'DELETE_COUPON',
      DOWNLOAD_COUPON: 'DOWNLOAD_COUPON'
    }
  },
  COLLECTION_MANAGEMENT: {
    key: 'COLLECTION_MANAGEMENT',
    permissions: {
      READ_COLLECTION: 'READ_COLLECTION',
      CREATE_COLLECTION: 'CREATE_COLLECTION',
      EDIT_COLLECTION: 'EDIT_COLLECTION',
      DELETE_COLLECTION: 'DELETE_COLLECTION',
      DOWNLOAD_COLLECTION: 'DOWNLOAD_COLLECTION'
    }
  },
  USER_MANAGEMENT: {
    key: 'USER_MANAGEMENT',
    permissions: {
      READ_USERS: 'READ_USERS',
      CREATE_USERS: 'CREATE_USERS',
      EDIT_USERS: 'EDIT_USERS',
      DELETE_USERS: 'DELETE_USERS',
      DOWNLOAD_USER: 'DOWNLOAD_USER'
    }
  },
  ROLE_MANAGEMENT: {
    key: 'ROLE_MANAGEMENT',
    permissions: {
      READ_ROLES: 'READ_ROLES',
      CREATE_ROLES: 'CREATE_ROLES',
      EDIT_ROLES: 'EDIT_ROLES',
      DELETE_ROLES: 'DELETE_ROLES',
      DOWNLOAD_ROLE: 'DOWNLOAD_ROLE'
    }
  },
  LANGUAGE_TRANSLATION_MANAGEMENT: {
    key: 'LANGUAGE_TRANSLATION_MANAGEMENT',
    permissions: {
      READ_LABELS: 'READ_LABELS',
      EDIT_LABELS: 'EDIT_LABELS',
      DOWNLOAD_LANGUAGE_TRANSLATION: 'DOWNLOAD_LANGUAGE_TRANSLATION'
    }
  },
  ZIP_CODE_MANAGEMENT: {
    key: 'ZIP_CODE_MANAGEMENT',
    permissions: {
      READ_ZIP_CODE: 'READ_ZIP_CODE',
      CREATE_ZIP_CODE: 'CREATE_ZIP_CODE',
      EDIT_ZIP_CODE: 'EDIT_ZIP_CODE',
      DELETE_ZIP_CODE: 'DELETE_ZIP_CODE',
      DOWNLOAD_ZIP_CODE: 'DOWNLOAD_ZIP_CODE'
    }
  },
  DELIVERY_MANAGEMENT: {
    key: 'DELIVERY_MANAGEMENT',
    permissions: {
      READ_DELIVERY_POLICY: 'READ_DELIVERY_POLICY',
      CREATE_DELIVERY_POLICY: 'CREATE_DELIVERY_POLICY',
      EDIT_DELIVERY_POLICY: 'EDIT_DELIVERY_POLICY',
      DELETE_DELIVERY_POLICY: 'DELETE_DELIVERY_POLICY',
      DOWNLOAD_DELIVERY: 'DOWNLOAD_DELIVERY'
    }
  },
  NAVIGATION_MANAGEMENT: {
    key: 'NAVIGATION_MANAGEMENT',
    permissions: {
      READ_NAVIGATION: 'READ_DELIVERY_POLICY',
      CREATE_NAVIGATION: 'CREATE_NAVIGATION',
      EDIT_NAVIGATION: 'EDIT_NAVIGATION',
      DELETE_NAVIGATION: 'DELETE_NAVIGATION',
      DOWNLOAD_NAVIGATION: 'DOWNLOAD_NAVIGATION'
    }
  },
  SPONSOR_MANAGEMENT: {
    key: 'SPONSOR_MANAGEMENT',
    permissions: {
      READ_SPONSOR: 'READ_SPONSOR',
      CREATE_SPONSOR: 'CREATE_SPONSOR',
      EDIT_SPONSOR: 'EDIT_SPONSOR',
      DELETE_SPONSOR: 'DELETE_SPONSOR',
      DOWNLOAD_SPONSOR: 'DOWNLOAD_SPONSOR'
    }
  },
  TAX_MANAGEMENT: {
    key: 'TAX_MANAGEMENT',
    permissions: {
      READ_TAX: 'READ_TAX',
      CREATE_TAX: 'CREATE_TAX',
      EDIT_TAX: 'EDIT_TAX',
      DELETE_TAX: 'DELETE_TAX',
      DOWNLOAD_TAX: 'DOWNLOAD_TAX'
    }
  },
  TICKET_MANAGEMENT: {
    key: 'TICKET_MANAGEMENT',
    permissions: {
      PRESCRIPTION_UPLOAD: 'PRESCRIPTION_UPLOAD',
      DOCTOR_CONSULTATION: 'DOCTOR_CONSULTATION',
      PRESCRIPTION_NOT_VERIFIED: 'PRESCRIPTION_NOT_VERIFIED',
      ORDER_NOT_DELIVERED: 'ORDER_NOT_DELIVERED',
      LATE_DELIVERY: 'LATE_DELIVERY',
      WRONG_MEDICINE_DELIVERED: 'WRONG_MEDICINE_DELIVERED',
      LOST_OR_MISSING_ITEMS_IN_DELIVERY: 'LOST_OR_MISSING_ITEMS_IN_DELIVERY',
      MANAGE_RETURN: 'MANAGE_RETURN',
      SUPPORT_TICKET_FULL_ACCESS: 'SUPPORT_TICKET_FULL_ACCESS',
      DOWNLOAD_TICKET: 'DOWNLOAD_TICKET'
    }
  },
  LOGISTICS_MANAGEMENT: {
    key: 'LOGISTICS_MANAGEMENT',
    permissions: {
      READ_LOGISTICS: 'READ_LOGISTICS',
      CREATE_LOGISTICS: 'CREATE_LOGISTICS',
      EDIT_LOGISTICS: 'EDIT_LOGISTICS',
      DELETE_LOGISTICS: 'DELETE_LOGISTICS',
      DOWNLOAD_LOGISTICS: 'DOWNLOAD_LOGISTICS'
    }
  },
  INVENTORY_MANAGEMENT: {
    key: 'INVENTORY_MANAGEMENT',
    permissions: {
      VIEW_INVENTORY: 'VIEW_INVENTORY',
      CREATE_INVENTORY: 'CREATE_INVENTORY',
      DOWNLOAD_INVENTORY: 'DOWNLOAD_INVENTORY'
    }
  },
  GENERAL_SETTING_MANAGEMENT: {
    key: 'GENERAL_SETTING_MANAGEMENT',
    permissions: {
      VIEW_GENERAL_SETTING: 'VIEW_GENERAL_SETTING',
      MANAGE_GENERAL_SETTING: 'MANAGE_GENERAL_SETTING',
      DOWNLOAD_GENERAL_SETTING: 'DOWNLOAD_GENERAL_SETTING'
    }
  },
  CUSTOMER_MANAGEMENT: {
    key: 'CUSTOMER_MANAGEMENT',
    permissions: {
      READ_CUSTOMER: 'READ_CUSTOMER',
      CREATE_CUSTOMER: 'CREATE_CUSTOMER',
      EDIT_CUSTOMER: 'EDIT_CUSTOMER',
      DELETE_CUSTOMER: 'DELETE_CUSTOMER',
      DOWNLOAD_CUSTOMER: 'DOWNLOAD_CUSTOMER'
    }
  },
  POLICY_MANAGEMENT: {
    key: 'POLICY_MANAGEMENT',
    permissions: {
      READ_POLICY: 'READ_POLICY',
      CREATE_POLICY: 'CREATE_POLICY',
      EDIT_POLICY: 'EDIT_POLICY',
      DELETE_POLICY: 'DELETE_POLICY',
      DOWNLOAD_POLICY: 'DOWNLOAD_POLICY'
    }
  },
  MEDICINE_REQUEST_MANAGEMENT: {
    key: 'MEDICINE_REQUEST_MANAGEMENT',
    permissions: {
      READ_MEDICINE_REQUEST: 'READ_MEDICINE_REQUEST',
      CREATE_MEDICINE_REQUEST: 'CREATE_MEDICINE_REQUEST',
      EDIT_MEDICINE_REQUEST: 'EDIT_MEDICINE_REQUEST',
      DELETE_MEDICINE_REQUEST: 'DELETE_MEDICINE_REQUEST',
      DOWNLOAD_MEDICINE_REQUEST: 'DOWNLOAD_MEDICINE_REQUEST'
    }
  }
}
