const QUEUE_NAME = 'commonQueue'
const CALLBACK_QUEUE_NAME = 'callbackQueue'
const ORDER_CHECKOUT_SESSION_QUEUE = 'orderCheckoutSession'
const BULK_UPLOAD_QUEUE = 'bulkUploadQueue'
const MEMBERSHIP_MANAGER_QUEUE = 'membershipManager'
const REFUND_PAYMENT_PROCESSED_QUEUE = 'refundPaymentProcessedQueue'
const ORDER_PROCESSING_QUEUE = 'orderProcessingQueue'
const PRESCRIPTION_GENERATION = 'prescriptionGenerationQueue'
const MEDICINE_REMAINDER_STOCK_NOTIFICATION_QUEUE = 'medicineRemainderStockNotificationQueue'
const ORDER_CHECKOUT_SESSION_TIMEOUT = 10 * 60 * 1000

export {
  QUEUE_NAME,
  CALLBACK_QUEUE_NAME,
  ORDER_CHECKOUT_SESSION_QUEUE,
  BULK_UPLOAD_QUEUE,
  MEMBERSHIP_MANAGER_QUEUE,
  REFUND_PAYMENT_PROCESSED_QUEUE,
  ORDER_PROCESSING_QUEUE,
  PRESCRIPTION_GENERATION,
  MEDICINE_REMAINDER_STOCK_NOTIFICATION_QUEUE,
  ORDER_CHECKOUT_SESSION_TIMEOUT
}
