import { SERVER_EVENTS } from './'
import { ALL_PROVIDERS, ProviderList } from '../constants/providerNames'

export const ALL_EVENT_PROVIDER_MAP: {
  [key: string]: ProviderList // 👈 This allows any string key
} = {
  // Auth Events
  [SERVER_EVENTS.ORDER_SHIPPED]: ALL_PROVIDERS,
  [SERVER_EVENTS.ORDER_DELIVERED]: ALL_PROVIDERS,
  [SERVER_EVENTS.ORDER_CANCELLED]: ALL_PROVIDERS,
  [SERVER_EVENTS.SUPPORT_TICKET_CLOSED]: ALL_PROVIDERS,
  [SERVER_EVENTS.SUPPORT_TICKET_CREATED]: ALL_PROVIDERS,
  [SERVER_EVENTS.REFUND_PROCESSED]: ALL_PROVIDERS,
  [SERVER_EVENTS.RETURN_PROCESSED]: ALL_PROVIDERS
}
